import type {
  LlmAnalyzeResult,
  ScriptPart
} from '../../../shared/segmentPipeline'
import {
  DEFAULT_STYLE_LOCK,
  createEmptyScriptPartClip,
  scriptPartsToFullScript
} from '../../../shared/segmentPipeline'
import { classifySceneVisualMode } from '../../../shared/pipelinePromptGuards'
import { generateId } from '../../../shared/types'
import type { LlmProvider } from '../../llm/llmProvider'
import { validateAnalysisResult } from '../validateAnalysis'
import { runCreativeBriefAgent } from './creativeBriefAgent'
import { runReferenceAgent } from './referenceAgent'
import { runScriptSegmentAgent } from './scriptSegmentAgent'
import { runImagePromptAgent } from './imagePromptAgent'
import { runImageCriticAgent } from './imageCriticAgent'
import { runVideoPromptAgent } from './videoPromptAgent'
import type {
  AgentBeatVisualMode,
  CreativeBriefExtraction,
  MultiAgentAnalyzeTrace,
  ReferencePlan,
  ScriptAnalysisDraft,
  ScriptSegmentDraft
} from './types'

export interface EnrichScriptPartsInput {
  parts: ScriptPart[]
  creativeInstructions?: string
  references?: Array<{ id: string; name: string; instruction: string }>
}

export interface EnrichScriptPartsResult {
  parts: ScriptPart[]
  analysis: LlmAnalyzeResult
  trace: MultiAgentAnalyzeTrace
}

interface FlatClipSeed {
  index: number
  partId: string
  clipId: string
  /** Narration for this beat (part text, or agent-split chunk). */
  scriptText: string
  explanation: string
  visualMode: AgentBeatVisualMode
  characters: string[]
  referenceIds?: string[]
  /** True when agents invented this clip (user left clips empty). */
  autoGenerated: boolean
}

function partHasUserClips(part: ScriptPart): boolean {
  return part.clips.some((c) => c.explanation.trim())
}

function toVisualMode(explanation: string, scriptText: string): AgentBeatVisualMode {
  return classifySceneVisualMode(explanation, scriptText) === 'diagram'
    ? 'diagram'
    : 'lifestyle'
}

function emptyBrief(): CreativeBriefExtraction {
  return {
    visualLook: '',
    lighting: '',
    colorPalette: '',
    diagramRules: '',
    lifestyleRules: '',
    forbiddenElements: [],
    brandTone: '',
    ignoredProcessNotes: [],
    summaryForPrompts: ''
  }
}

/**
 * Build clip seeds: user visuals when provided; otherwise script-segment agent invents clips.
 * fullScript is always the combined narration of all parts.
 */
async function buildSeedsFromParts(
  provider: LlmProvider,
  parts: ScriptPart[],
  creativeBrief: CreativeBriefExtraction,
  referencePlan: ReferencePlan,
  referenceIds: string[],
  agentTrace: MultiAgentAnalyzeTrace['agents']
): Promise<{
  seeds: FlatClipSeed[]
  characters: ScriptAnalysisDraft['characters']
  styleLock: ScriptAnalysisDraft['styleLock']
}> {
  const seeds: FlatClipSeed[] = []
  const charactersById = new Map<string, ScriptAnalysisDraft['characters'][number]>()
  let styleLock = { ...DEFAULT_STYLE_LOCK }

  const ordered = [...parts].sort((a, b) => a.index - b.index)
  for (const part of ordered) {
    const scriptText = part.scriptText.trim()
    if (!scriptText) continue

    if (partHasUserClips(part)) {
      for (const clip of part.clips) {
        const explanation = clip.explanation.trim()
        if (!explanation) continue
        seeds.push({
          index: seeds.length,
          partId: part.id,
          clipId: clip.id,
          scriptText,
          explanation,
          visualMode: toVisualMode(explanation, scriptText),
          characters: [],
          referenceIds: referenceIds.length ? [...referenceIds] : undefined,
          autoGenerated: false
        })
      }
      continue
    }

    // No user clips — invent visual beats for this part.
    const tSeg = Date.now()
    try {
      const draft = await runScriptSegmentAgent(
        provider,
        scriptText,
        creativeBrief,
        referencePlan
      )
      agentTrace.push({
        agent: `script-segment:part-${part.index + 1}`,
        ok: true,
        ms: Date.now() - tSeg
      })

      for (const c of draft.characters) {
        if (!charactersById.has(c.id)) {
          charactersById.set(c.id, {
            ...c,
            role: c.role?.trim() || 'character'
          })
        }
      }

      if (draft.styleLock.visualStyle?.trim()) {
        styleLock = {
          ...styleLock,
          ...draft.styleLock,
          visualStyle: draft.styleLock.visualStyle
        }
      }

      for (const seg of draft.segments) {
        seeds.push({
          index: seeds.length,
          partId: part.id,
          clipId: generateId(),
          scriptText: seg.scriptText.trim() || scriptText,
          explanation: seg.beatSummary.trim() || seg.scriptText.slice(0, 120),
          visualMode: seg.visualMode,
          characters: seg.characters,
          referenceIds:
            seg.referenceIds?.length
              ? seg.referenceIds
              : referenceIds.length
                ? [...referenceIds]
                : undefined,
          autoGenerated: true
        })
      }
    } catch (err) {
      agentTrace.push({
        agent: `script-segment:part-${part.index + 1}`,
        ok: false,
        ms: Date.now() - tSeg,
        error: err instanceof Error ? err.message : String(err)
      })
      // Fallback: one clip covering the whole part.
      seeds.push({
        index: seeds.length,
        partId: part.id,
        clipId: generateId(),
        scriptText,
        explanation: `Visual for: ${scriptText.slice(0, 160)}`,
        visualMode: toVisualMode(scriptText, scriptText),
        characters: [],
        referenceIds: referenceIds.length ? [...referenceIds] : undefined,
        autoGenerated: true
      })
    }
  }

  return {
    seeds,
    characters: [...charactersById.values()],
    styleLock
  }
}

function buildDraftFromSeeds(
  seeds: FlatClipSeed[],
  characters: ScriptAnalysisDraft['characters'],
  styleLock: ScriptAnalysisDraft['styleLock'],
  creativeBrief: CreativeBriefExtraction
): ScriptAnalysisDraft {
  const segments: ScriptSegmentDraft[] = seeds.map((seed, i) => ({
    index: seed.index,
    scriptText: seed.scriptText,
    visualMode: seed.visualMode,
    characters: seed.characters.filter((id) => characters.some((c) => c.id === id)),
    continuityFromPrevious: i > 0,
    beatSummary: seed.explanation,
    referenceIds: seed.referenceIds
  }))

  let nextStyle = { ...styleLock }
  if (creativeBrief.summaryForPrompts.trim()) {
    const hint = creativeBrief.summaryForPrompts.trim()
    const visualStyle = nextStyle.visualStyle?.trim() || ''
    nextStyle = {
      ...nextStyle,
      visualStyle: visualStyle.toLowerCase().includes(hint.slice(0, 40).toLowerCase())
        ? visualStyle
        : visualStyle
          ? `${visualStyle}. ${hint}`
          : hint
    }
  }

  return { segments, characters, styleLock: nextStyle }
}

/**
 * Parts mode:
 * - User parts → combined fullScript
 * - Clip visuals when provided → fixed beats
 * - Parts without clips → script-segment agent invents clips
 * - Then image → critic → video agents (same as Analyze)
 */
export async function enrichScriptPartsWithAgents(
  provider: LlmProvider,
  input: EnrichScriptPartsInput
): Promise<EnrichScriptPartsResult> {
  const partsWithText = input.parts.filter((p) => p.scriptText.trim())
  if (partsWithText.length === 0) {
    throw new Error('Add at least one script part with text before building.')
  }

  const fullScript = scriptPartsToFullScript(input.parts)
  const referenceIds = (input.references ?? []).map((r) => r.id)
  const agentTrace: MultiAgentAnalyzeTrace['agents'] = []

  const tCreative = Date.now()
  let creativeBrief: CreativeBriefExtraction
  try {
    creativeBrief = await runCreativeBriefAgent(provider, input.creativeInstructions)
    agentTrace.push({ agent: 'creative-brief', ok: true, ms: Date.now() - tCreative })
  } catch (err) {
    creativeBrief = emptyBrief()
    agentTrace.push({
      agent: 'creative-brief',
      ok: false,
      ms: Date.now() - tCreative,
      error: err instanceof Error ? err.message : String(err)
    })
  }

  const tRefs = Date.now()
  let referencePlan: ReferencePlan
  try {
    referencePlan = await runReferenceAgent(provider, input.references)
    agentTrace.push({ agent: 'reference-plan', ok: true, ms: Date.now() - tRefs })
  } catch (err) {
    referencePlan = { items: [], globalGuidance: '' }
    agentTrace.push({
      agent: 'reference-plan',
      ok: false,
      ms: Date.now() - tRefs,
      error: err instanceof Error ? err.message : String(err)
    })
  }

  // Guarantee every attached reference appears in the plan (agent may omit some).
  if (input.references?.length) {
    const known = new Set(referencePlan.items.map((i) => i.id))
    for (const ref of input.references) {
      if (!ref.id || known.has(ref.id)) continue
      referencePlan.items.push({
        id: ref.id,
        name: ref.name || 'reference',
        usageSummary: ref.instruction.trim() || 'Match this attached reference image where it applies.',
        appliesToModes: ['lifestyle', 'diagram', 'product'],
        priority: 'required'
      })
      known.add(ref.id)
    }
  }

  const { seeds, characters, styleLock } = await buildSeedsFromParts(
    provider,
    input.parts,
    creativeBrief,
    referencePlan,
    referenceIds,
    agentTrace
  )

  if (seeds.length === 0) {
    throw new Error('Could not build any clips from the script parts.')
  }

  const scriptDraft = buildDraftFromSeeds(seeds, characters, styleLock, creativeBrief)
  // Ensure every beat carries all attached reference ids for prompt + image enqueue.
  if (referenceIds.length > 0) {
    scriptDraft.segments = scriptDraft.segments.map((s) => ({
      ...s,
      referenceIds: [...referenceIds]
    }))
  }

  console.log('[Pipeline · parts] Multi-agent enrich starting', {
    parts: partsWithText.length,
    clips: seeds.length,
    autoClips: seeds.filter((s) => s.autoGenerated).length,
    userClips: seeds.filter((s) => !s.autoGenerated).length,
    fullScriptLength: fullScript.length,
    hasCreative: Boolean(input.creativeInstructions?.trim()),
    references: referenceIds.length,
    referenceIds
  })

  const tImage = Date.now()
  let imageMap: Map<number, string>
  try {
    imageMap = await runImagePromptAgent(
      provider,
      scriptDraft,
      creativeBrief,
      referencePlan
    )
    agentTrace.push({ agent: 'image-prompt', ok: true, ms: Date.now() - tImage })
  } catch (err) {
    agentTrace.push({
      agent: 'image-prompt',
      ok: false,
      ms: Date.now() - tImage,
      error: err instanceof Error ? err.message : String(err)
    })
    throw err instanceof Error ? err : new Error(String(err))
  }

  let imagePrompts: Record<number, string> = {}
  for (const [index, prompt] of imageMap) imagePrompts[index] = prompt

  const tCritic = Date.now()
  try {
    const critic = await runImageCriticAgent(provider, scriptDraft, imagePrompts)
    imagePrompts = { ...imagePrompts, ...critic.revisedPrompts }
    agentTrace.push({ agent: 'image-critic', ok: true, ms: Date.now() - tCritic })
  } catch (err) {
    agentTrace.push({
      agent: 'image-critic',
      ok: false,
      ms: Date.now() - tCritic,
      error: err instanceof Error ? err.message : String(err)
    })
  }

  const tVideo = Date.now()
  let videoMap: Map<number, string>
  try {
    videoMap = await runVideoPromptAgent(
      provider,
      scriptDraft,
      new Map(Object.entries(imagePrompts).map(([k, v]) => [Number(k), v])),
      creativeBrief
    )
    agentTrace.push({ agent: 'video-prompt', ok: true, ms: Date.now() - tVideo })
  } catch (err) {
    agentTrace.push({
      agent: 'video-prompt',
      ok: false,
      ms: Date.now() - tVideo,
      error: err instanceof Error ? err.message : String(err)
    })
    throw err instanceof Error ? err : new Error(String(err))
  }

  const videoPrompts: Record<number, string> = {}
  for (const [index, prompt] of videoMap) videoPrompts[index] = prompt

  const knownRefs = new Set(referenceIds)
  const characterIds = new Set(scriptDraft.characters.map((c) => c.id))
  // Always stamp every attached reference onto every clip for Parts builds.
  const assembled = {
    segments: scriptDraft.segments.map((s) => ({
      index: s.index,
      scriptText: s.scriptText,
      imagePrompt: imagePrompts[s.index] ?? s.beatSummary,
      videoMotionPrompt: videoPrompts[s.index],
      characters: s.characters.filter((id) => characterIds.has(id)),
      continuityFromPrevious: s.continuityFromPrevious,
      referenceIds: referenceIds.length
        ? [...referenceIds]
        : (s.referenceIds ?? []).filter((id) => knownRefs.has(id)),
      sourcePartId: seeds[s.index]?.partId,
      sourceClipId: seeds[s.index]?.clipId
    })),
    characters: scriptDraft.characters.map((c) => ({
      ...c,
      role: c.role?.trim() || 'character'
    })),
    styleLock: scriptDraft.styleLock
  }

  const analysis = validateAnalysisResult(assembled, knownRefs, {
    fullScript,
    enforceExactScript: false,
    expectedSegmentCount: seeds.length
  })

  analysis.segments = analysis.segments.map((seg, i) => ({
    ...seg,
    sourcePartId: seeds[i]?.partId ?? seeds.find((s) => s.index === seg.index)?.partId,
    sourceClipId: seeds[i]?.clipId ?? seeds.find((s) => s.index === seg.index)?.clipId
  }))

  const seedsByPart = new Map<string, FlatClipSeed[]>()
  for (const seed of seeds) {
    const list = seedsByPart.get(seed.partId) ?? []
    list.push(seed)
    seedsByPart.set(seed.partId, list)
  }

  const enrichedParts = input.parts.map((part) => {
    const partSeeds = seedsByPart.get(part.id)
    if (!partSeeds?.length) return part

    if (partHasUserClips(part)) {
      return {
        ...part,
        clips: part.clips.map((clip) => {
          const seed = partSeeds.find((s) => s.clipId === clip.id)
          if (!seed) return clip
          const seg = analysis.segments.find((s) => s.sourceClipId === clip.id)
          return {
            ...clip,
            imagePrompt: seg?.imagePrompt ?? clip.imagePrompt,
            videoMotionPrompt: seg?.videoMotionPrompt ?? clip.videoMotionPrompt
          }
        })
      }
    }

    // Replace empty/placeholder clips with agent-invented ones.
    return {
      ...part,
      clips: partSeeds.map((seed) => {
        const seg = analysis.segments.find((s) => s.sourceClipId === seed.clipId)
        return {
          ...createEmptyScriptPartClip(),
          id: seed.clipId,
          explanation: seed.explanation,
          imagePrompt: seg?.imagePrompt ?? '',
          videoMotionPrompt: seg?.videoMotionPrompt ?? ''
        }
      })
    }
  })

  console.log('[Pipeline · parts] Multi-agent enrich complete', {
    clips: analysis.segments.length,
    fullScriptLength: fullScript.length,
    agents: agentTrace.map((a) => `${a.agent}:${a.ok ? 'ok' : 'fail'}(${a.ms}ms)`)
  })

  return {
    parts: enrichedParts,
    analysis,
    trace: { mode: 'multi-agent', agents: agentTrace }
  }
}
